# Generated by Django 2.1.3 on 2018-11-10 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20181109_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='status_code',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='site',
            name='last_check_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 10, 22, 20, 43, 220049)),
        ),
    ]
