# Generated by Django 2.1.3 on 2018-11-10 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20181110_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='last_check_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 10, 23, 10, 37, 548676)),
        ),
    ]
