# Generated by Django 2.1.3 on 2018-11-12 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20181110_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='update_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='last_check_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
