# Generated by Django 2.1.3 on 2018-11-13 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0006_site_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FcmDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(max_length=1200, unique=True)),
                ('brand', models.CharField(max_length=200)),
                ('build_number', models.CharField(max_length=200)),
                ('device_id', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('device_name', models.CharField(max_length=400)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fcm Token',
            },
        ),
    ]
