# Generated by Django 2.1.3 on 2018-11-13 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_fcmdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='last_access_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
